name: Build and publish Docker image to GitHub packages
on:
  push:
    branches: ['deployment-test']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - run: echo "Login to ${{ env.REGISTRY }}"
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set short commit SHA
        env:
          COMMIT_SHA: ${{ github.sha }}
        run: echo "COMMIT_SHA=$(git rev-parse --short $COMMIT_SHA)" >> $GITHUB_ENV

      - name: Use short commit SHA
        env:
          COMMIT_SHA: ${{ env.COMMIT_SHA }}
        run: echo "The short commit SHA is $COMMIT_SHA"

#      - name: Build and push Docker image
#        id: push
#        uses: docker/build-push-action@v6
#        with:
#          context: .
#          file: docker/Dockerfile
#          push: true
#          tags: ${{ env.IMAGE_NAME }}
